### ISSUE TITLE
Add a deploy to heroku button

### ISSUE THREAD

**Issue by LemonAndroid** [icetiger-tec/couchpotatoe#2]

**Comment by chinhai077** [comment]
What's the problem exactly?

**Comment by LemonAndroid** [comment]
The app must be deployable to Heroku by clicking a "Deploy to Heroku" button in the README.

**Comment by LemonAndroid** [comment]
@chinhai077 

Defining depoyable:

Once the app is deployed, it is possible to sign up and log in afterwards via the web interface.

**Comment by LemonAndroid** [comment]
@mejiaro 
Thanks for your contribution.

**Comment by LemonAndroid** [comment]
https://github.com/icetiger-tec/couchpotatoe/pull/3/files

```

       Bundle completed (56.50s)
       Cleaning up the bundler cache.
-----> Installing node-v8.10.0-linux-x64
-----> Detecting rake tasks
 !
 !     Argument list too long -  logger -p user.notice -t "slugc[$$]" "buildpack-ruby compile id=17673abaa6b framework=rails42 status=error finish=1533347344.10 elapsed=61.44 message=Argument\ list\ too\ long\ -\ \ logger\ -p\ user.notice\ -t\ \"slugc\[\$\$\]\"\ \"buildpack-ruby\ assets_precompile\ id\=17673abaa6b\ framework\=rails42\ status\=error\ finish\=1533347343.99\ elapsed\=1.55\ message\=Could\\\ not\\\ detect\\\ rake\\\ tasks\''
 !     '\'ensure\\\ you\\\ can\\\ run\\\ \\\`\\\$\\\ bundle\\\ exec\\\ rake\\\ -P\\\`\\\ against\\\ your\\\ app\''
 !     '\'and\\\ using\\\ the\\\ production\\\ group\\\ of\\\ your\\\ Gemfile.\''
 !     '\'/tmp/build_f8b727a79e6ee9243853914382deaa97/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:121:\\\ warning:\\\ constant\\\ ::Fixnum\\\ is\\\ deprecated\''
 !     '\'/tmp/build_f8b727a79e6ee9243853914382deaa97/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:121:\\\ warning:\\\ constant\\\ ::Bignum\\\ is\\\ deprecated\''
 !     '\'rake\\\ aborted\\\!\''
 !     '\'SystemStackError:\\\ stack\\\ level\\\ too\\\ deep\''
 !     '\'/tmp/build_f8b727a79e6ee9243853914382deaa97/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:124:in\\\ \\\`block\\\ \\\(2\\\ levels\\\)\\\ in\\\ \\\<class:Numeric\\\>\\\'\''
 !     '\'/tmp/build_f8b727a79e6ee9243853914382deaa97/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:131:in\\\ \\\`block\\\ \\\(2\\\ levels\\\)\\\ in\\\ \\\<class:Numeric
```

The log is much longer than that, it's easily reproducable by clicking the "Deploy to Heroku" button in the README.

**Comment by mejiaro** [comment]
Hi @LemonAndroid ,

I understand, but the reasons why the app is not deploying are beyond the scope of the bounty posted on Bounty Source. If you'd like to fix this issue please contact me directly or create a new issue with a new bounty.

Cheers.

**Comment by LemonAndroid** [comment]
@mejiaro How would you describe the scope of this issue?

**Comment by LemonAndroid** [comment]
- [ ] Add postgres to the heroku configuration
- [ ] Add execution of database migrations to the heroku configuration
- [ ] figure out the csrf issue on /users/login_and_registrations
- [ ] check on /users/login_and_registration, that a sign up followed by a login works

**Comment by LemonAndroid** [comment]
@mejiaro If you complete the first 2 todos from the list in the previous commit, I'm fine with awarding you the bounty.

**Comment by mejiaro** [comment]
Fair enough. I already added it on my local repo, the version of mysql you are using is old, and was giving me problems with newer versions of SQL.

**Comment by LemonAndroid** [comment]
It needs to be postgresql for heroku afaik. Just ignore mysql for now, I don't like Oracle anyways :D.

**Comment by mejiaro** [comment]
There are some MySQL providers, but I've found it easier to work with
Postgres.

**Comment by LemonAndroid** [comment]
https://github.com/LemonAndroid/qanda-wikipedia/issues/28 I needed a quick way to add funds for this issue

**Comment by LemonAndroid** [comment]
Have you made progress?

**Comment by LemonAndroid** [comment]
I will still award the bounty, dont worry.

**Comment by LemonAndroid** [comment]
@mejiaro Can you give me an estimate, when there will be new progress on this issue?

**Comment by LemonAndroid** [comment]
I will no continue with doing these todos. Bountysource is a competition after all, and I'm allowed to partake as well.

**Comment by LemonAndroid** [comment]
done https://jfowiejfiwoef.herokuapp.com/users/login_and_registration

**Comment by mejiaro** [comment]
Sorry, I didn't intend to make fun of you. You are right you can claim the county too. Good thing it's working now! 👍

**Comment by mejiaro** [comment]
that last one on the to-do list id because you've commented out the csrf-meta tags on the application.html.haml layout

**Comment by LemonAndroid** [comment]
@mejiaro
Can you claim the current 25$ bounty on bountysource?

For the csrf and other stuff I will create new issues.

Thx!

**Comment by mejiaro** [comment]
No man, it says it's already paid out.

**Comment by LemonAndroid** [comment]
I will contact support.

**Comment by LemonAndroid** [comment]
Hey @mejiaro 

I was just contacted by support, they asked for you to request a cash out for the amount (25$) which they will then accept.

I just need your bountysource username once you did that.

**Comment by mejiaro** [comment]
Oh wow, thanks. My username is mejiaro, but I can't cash out. it says I have no eligible cashouts :/

If it becomes too tedious don't worry about it. Maybe just my contribution to OSS will look good my account haha

**Comment by LemonAndroid** [comment]
@mejiaro 25$ should now be credited to your account on bountysource. Please confirm.
